apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/devops-todo-backend:latest
        ports:
        - containerPort: 5000
      - name: frontend
        image: your-dockerhub-username/devops-todo-frontend:latest
        ports:
        - containerPort: 80
