name: DevOps Project CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3. Install backend dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/backend/requirements.txt

      # 4. Run backend tests
      - name: Run tests
        run: python -m pytest test/test_app.py
          # pytest test/test_app.py

      # 5. Build backend Docker image
      - name: Build backend image
        run: docker build -t davidrosario26387/todo-backend:latest -f Dockerfile.backend .

      # 6. Build frontend Docker image
      - name: Build frontend image
        run: docker build -t davidrosario26387/todo-frontend:latest -f Dockerfile.frontend .

      # 7. Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Push images to Docker Hub
      - name: Push backend image
        run: docker push davidrosario26387/todo-backend:latest

      - name: Push frontend image
        run: docker push davidrosario26387/todo-frontend:latest
